name: HolaMundo

on: 
  push: 
    branches:
       - main
       - develop
       - releases
       - hotfix

jobs:
  Saludos:
    runs-on: ubuntu-latest

    steps:
      - name: descargar el repo âš¡
        uses: actions/checkout@v4

      - name: Hola Push ðŸ””
        run: echo "hola mundo desde github actions on push"

      - name: Hola desde el ambiente Develop ðŸ˜Š
        if: ${{github.ref == 'refs/heads/develop'}}
        run: echo "hola desde la rama develop"

      - name: Hola desde el ambiente Main ðŸ˜Ž  
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "hola desde la rama main"

        
